name: Run all checks
on:
    push:
    pull_request:
        branches: ['master', 'development']
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2-beta
              with:
                  node-version: 16.x

            - name: npm install
              run: npm ci

            - name: Run linter
              run: npm run lint

    unit-tests:
        needs: lint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.client_payload.sha }}

            - uses: actions/setup-node@v2-beta
              with:
                  node-version: 16.x

            - name: npm install
              run: npm ci

            - name: Run unit tests
              run: npm run test

    e2e-tests:
        needs: [lint, unit-tests]
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.client_payload.sha }}

            - uses: actions/setup-node@v2-beta
              with:
                  node-version: 16.x

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.6.0
              with:
                  mongodb-version: 4.4.4
            - name: npm install
              run: npm ci
            - name: Run run e2e tests
              run: npm run test:e2e
              env:
                  USE_LOCAL_MONGO_HOST: true

    publish-docker-image:
        needs: [lint, unit-tests, e2e-tests]
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.client_payload.sha }}

            - uses: actions/checkout@master
            - name: Publish to registry
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  registry: docker.pkg.github.com
                  name: docker.pkg.github.com/wavilikhin/nest-api/nest-api
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  tags: development
